In [1]:
import pandas as pd

In [13]:
data=pd.DataFrame({"text":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"],"output":[1,1,0,0]})

In [9]:
# Document Matrix(BOW)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
data.head()

text  output
0   people watch ineuron       1
1  ineuron watch ineuron       1
2   people write comment       0
3  ineuron write comment       0

In [15]:
BOW=CountVectorizer()

In [17]:
document_matrix=BOW.fit_transform(data["text"])

In [18]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [19]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [25]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]], dtype=int64)

In [26]:
document_matrix[1].toarray()

array([[0, 2, 0, 1, 0]], dtype=int64)

In [27]:
document_matrix[2].toarray()

array([[1, 0, 1, 0, 1]], dtype=int64)

In [29]:
document_matrix[3].toarray()

array([[1, 1, 0, 0, 1]], dtype=int64)

In [40]:
bi_gram=CountVectorizer(ngram_range=(2,2))

In [41]:
bigram_voc=bi_gram.fit_transform(data["text"])

In [42]:
bi_gram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [45]:
tri_gram=CountVectorizer(ngram_range=(3,3))

In [46]:
tri_voc=tri_gram.fit_transform(data["text"])

In [47]:
tri_gram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [51]:
sing_bi_gram=CountVectorizer(ngram_range=(1,2))

In [56]:
sing_bi_voc=sing_bi_gram.fit_transform(data["text"])

In [58]:
sing_bi_gram.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer 

In [60]:
tfidf=TfidfVectorizer()

In [62]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [64]:
tfidf.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [66]:
# Inverse document function
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])